apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack
    receivers:
      - uid: slack-receiver
        type: slack
        settings:
          url: $SLACK_WEBHOOK_URL
          httpMethod: POST
          title: |
            {{ if eq .Status "firing" }}[{{ .CommonLabels.severity | toUpper }}] {{ .CommonAnnotations.summary }}{{ else }}[RESOLVED] {{ .CommonAnnotations.summary }}{{ end }}
          text: |
            {{ .CommonAnnotations.description }}
        disableResolveMessage: false
