apiVersion: 1

policies:
  - orgId: 1
    receiver: Slack
    group_by:
      - alertname
    group_wait: 10s
    group_interval: 1m
    repeat_interval: 5m
    routes:
      - receiver: Slack
        matchers:
          - severity = info
        repeat_interval: 2m
      - receiver: Slack
        matchers:
          - severity = warning
        repeat_interval: 4m