FROM grafana/grafana:latest

COPY provisioning /etc/grafana/provisioning
COPY dashboards /etc/grafana/dashboards
COPY dashboards/node-overview.json /etc/grafana/dashboards/monitoring/node-overview.json
